# Generated by Django 3.0.8 on 2020-07-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('release_date', models.DateField()),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
