# Generated by Django 3.0.8 on 2020-07-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
    ]
