# Generated by Django 3.0.8 on 2020-08-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200724_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_link',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
